apiVersion: v2
name: pihole
version: 0.1.0
appVersion: "latest"
description: Helm chart for Pi-hole, a network-wide ad blocker
home: https://github.com/santisbon/pi-hole
maintainers:
  - name: santisbon
