{{- if not .Values.credentials.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pihole.fullname" . }}-credentials
  labels:
    {{- include "pihole.labels" . | nindent 4 }}
type: Opaque
stringData:
  web-password: {{ required "credentials.webPassword is required when credentials.existingSecret is not set" .Values.credentials.webPassword | quote }}
{{- end }}
