apiVersion: v1
kind: Service
metadata:
  name: {{ include "pihole.fullname" . }}-dns
  labels:
    {{- include "pihole.labels" . | nindent 4 }}
  {{- with .Values.dnsService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.dnsService.type }}
  {{- if .Values.dnsService.loadBalancerIP }}
  loadBalancerIP: {{ .Values.dnsService.loadBalancerIP }}
  {{- end }}
  selector:
    {{- include "pihole.selectorLabels" . | nindent 4 }}
  ports:
    - name: dns-tcp
      protocol: TCP
      port: 53
      targetPort: dns-tcp
    - name: dns-udp
      protocol: UDP
      port: 53
      targetPort: dns-udp
